# Generated by Django 5.2.5 on 2025-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('sector', models.CharField(max_length=100, verbose_name='Sector de actividad')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tiene_politica_ambiental', models.BooleanField(verbose_name='¿La empresa tiene una política ambiental?')),
                ('cumple_normativa_local', models.BooleanField(verbose_name='¿Cumple con la normativa ambiental local?')),
                ('realiza_auditorias', models.BooleanField(verbose_name='¿Realiza auditorías ambientales periódicas?')),
                ('gestiona_residuos', models.BooleanField(verbose_name='¿Gestiona adecuadamente sus residuos?')),
                ('usa_energia_renovable', models.BooleanField(verbose_name='¿Utiliza fuentes de energía renovable?')),
                ('mide_consumo_agua', models.BooleanField(verbose_name='¿Mide y controla el consumo de agua?')),
                ('tiene_plan_emergencia', models.BooleanField(verbose_name='¿Tiene plan de emergencia ambiental?')),
                ('involucra_empleados', models.BooleanField(verbose_name='¿Involucra a los empleados en prácticas sostenibles?')),
                ('comunica_transparente', models.BooleanField(verbose_name='¿Comunica de forma transparente sus acciones?')),
                ('colabora_comunidad', models.BooleanField(verbose_name='¿Colabora con la comunidad local?')),
                ('promueve_igualdad', models.BooleanField(verbose_name='¿Promueve la igualdad y diversidad?')),
                ('evalua_proveedores', models.BooleanField(verbose_name='¿Evalúa la sostenibilidad de sus proveedores?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
            ],
        ),
    ]
