# Generated by Django 5.2.5 on 2025-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones adicionales'),
        ),
    ]
